# Generated by Django 4.2.5 on 2023-10-22 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
    ]
